USE users_management;

CREATE TABLE SCHEDULE
(
  Id INT AUTO_INCREMENT primary key,
  CustomerCourseId INT,
  CoachId INT,
  FOREIGN KEY (CustomerCourseId) REFERENCES CUSTOMER_COURSE(Id) ON DELETE CASCADE,
  FOREIGN KEY (CoachId) REFERENCES EMPLOYEE(Id) ON DELETE CASCADE
);